# Generated by Django 5.2 on 2025-04-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('phone', models.IntegerField(default=0)),
                ('adress', models.IntegerField(default=0)),
                ('city', models.CharField(default=0)),
            ],
        ),
    ]
