# Generated by Django 5.2 on 2025-04-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q3app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='adress',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='human',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='human',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
