# Generated by Django 5.2 on 2025-04-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q3app', '0002_alter_human_adress_alter_human_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='human',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='human',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='human',
            name='adress',
        ),
        migrations.AddField(
            model_name='human',
            name='address',
            field=models.CharField(default='ADF', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='human',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
